extends Node
signal ingredient_added(ingredient)
signal ingredients_reset
signal item_added(item)
signal item_sold(item)
signal price_set(item)
signal customer_clicked()
signal customer_interested(item)
signal player_money_updated(money)